//
// Proposals: the shapes, the bounds, and the form token.
//
// docs/PROPOSALS.md §8 build step 2 is the `break` type only — "here is a case
// this division cannot classify". It is first because it is the most valuable
// and the easiest to submit: it needs a case, not a replacement structure.
//
// Nothing here knows about the other four types. When they arrive they bring
// their own payload shape and their own bounds, and this file gains a branch
// rather than a generalisation written before there was anything to generalise.
//
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Bounds ----------------------------------------------------------------------

const BODY_MAX = 4000;          // §4: "the argument, markdown, 4000 chars"
const CASE_MAX = 1000;
const SOURCE_MAX = 300;
const SOURCES_MAX = 20;

// §4: "Honeypot field plus minimum time-on-form of 20 seconds".
const MIN_SECONDS_ON_FORM = 20;

// A form left open overnight and submitted in the morning is a real person, so
// this is generous. It exists so a token cannot be minted once and reused by a
// script for a month.
const FORM_TOKEN_MAX_AGE_MS = 24 * 60 * 60 * 1000;


// The atlas -------------------------------------------------------------------
//
// §4: `node_path` "resolves in the current atlas". The atlas is YAML under
// version control and is not in this database, so the set of valid paths is
// generated by scripts/atlas-paths.mjs and committed into api/. Read once at
// startup: it changes when the service is redeployed and not otherwise.

const PATHS = (() => {
    const file = path.join(__dirname, '..', 'atlas-paths.json');
    try {
        return new Set(JSON.parse(fs.readFileSync(file, 'utf8')).paths);
    } catch (err) {
        // Refusing to start is right. Without this file every proposal would be
        // rejected as pointing at an unknown node, which looks like a bad
        // submission rather than a broken deploy.
        throw new Error(
            `Could not read atlas-paths.json (${err.message}). ` +
            'Run `npm run atlas:paths` at the repository root and commit the result.'
        );
    }
})();

function knownNodePath(value) {
    return typeof value === 'string' && PATHS.has(value);
}


// Field checks ----------------------------------------------------------------
//
// Each returns a sentence to show the person, or null. Same shape as
// src/accounts.js, so a route reads the same way whichever it is calling.

function nodePathProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'Which node is this about?';
    }
    if (!knownNodePath(value.trim())) {
        return 'That node is not in the atlas. Check the path from the node page URL.';
    }
    return null;
}

function caseProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'A break needs a case: the thing the division cannot classify.';
    }
    if (value.trim().length > CASE_MAX) {
        return `The case is limited to ${CASE_MAX} characters. The argument below has room.`;
    }
    return null;
}

function bodyProblem(value) {
    if (typeof value !== 'string' || value.trim() === '') {
        return 'Say why the division cannot classify it.';
    }
    if (value.trim().length > BODY_MAX) {
        return `The argument is limited to ${BODY_MAX} characters.`;
    }
    return null;
}

function displayAsProblem(value) {
    if (value !== 'name' && value !== 'anonymous') {
        return 'Choose whether to publish under your display name or anonymously.';
    }
    return null;
}

// Absent, empty, or a list of non-empty strings. Empty is allowed: §4 warns on
// the form when there are no sources but does not refuse, because a break can
// be a case nobody has written up.
function sourcesProblem(value) {
    if (value === undefined || value === null) return null;
    if (!Array.isArray(value)) return 'Sources must be a list.';
    if (value.length > SOURCES_MAX) {
        return `At most ${SOURCES_MAX} sources.`;
    }
    for (const entry of value) {
        if (typeof entry !== 'string') return 'Each source must be a line of text.';
        if (entry.trim().length > SOURCE_MAX) {
            return `Each source is limited to ${SOURCE_MAX} characters.`;
        }
    }
    return null;
}

function cleanSources(value) {
    if (!Array.isArray(value)) return [];
    return value.map((s) => String(s).trim()).filter((s) => s !== '');
}


// The form token --------------------------------------------------------------
//
// §4 asks for a minimum time-on-form of 20 seconds, server-side. The form is a
// static page, so the server cannot know when it was opened unless it says so
// itself: GET /atlas/proposals/new issues a token carrying the issue time and
// an HMAC of it, and the submission carries it back.
//
// An elapsed-milliseconds number sent by the page would have been simpler and
// would have checked nothing — the value a script sends is the value it wants
// to send. This is signed, so the only way to satisfy the check is to have
// asked for the form and waited.

const SECRET = (() => {
    if (process.env.FORM_SECRET) return process.env.FORM_SECRET;
    // A per-process secret still works, and keeps the service deployable
    // without a new variable. The cost is that tokens issued before a restart
    // are refused afterwards, and the person is asked to reload — so it is
    // worth setting FORM_SECRET in production, and worth saying why here
    // rather than failing on boot over something recoverable.
    if (process.env.NODE_ENV === 'production') {
        console.warn(
            'FORM_SECRET is not set — proposal form tokens will not survive a restart.'
        );
    }
    return crypto.randomBytes(32).toString('hex');
})();

function sign(issuedAt) {
    return crypto.createHmac('sha256', SECRET).update(String(issuedAt)).digest('hex');
}

function issueFormToken(now = Date.now()) {
    return `${now}.${sign(now)}`;
}

// Returns a sentence or null. Deliberately does not distinguish "forged" from
// "expired" to the caller beyond what the person needs to do about it.
function formTokenProblem(token, now = Date.now()) {
    if (typeof token !== 'string' || !token.includes('.')) {
        return 'This form has expired. Reload the page and try again.';
    }

    const [issuedAtRaw, mac] = token.split('.', 2);
    const issuedAt = Number(issuedAtRaw);
    if (!Number.isFinite(issuedAt)) {
        return 'This form has expired. Reload the page and try again.';
    }

    const expected = sign(issuedAtRaw);
    const a = Buffer.from(String(mac), 'utf8');
    const b = Buffer.from(expected, 'utf8');
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
        return 'This form has expired. Reload the page and try again.';
    }

    const age = now - issuedAt;
    if (age > FORM_TOKEN_MAX_AGE_MS || age < 0) {
        return 'This form has expired. Reload the page and try again.';
    }
    if (age < MIN_SECONDS_ON_FORM * 1000) {
        return 'Take a moment longer over it — a proposal is read by a person.';
    }
    return null;
}


// The public shape ------------------------------------------------------------
//
// What a submitter is told back about their own proposal. Not the review
// queue's shape: decision_reason and the account behind an anonymous
// submission belong to §6 and are not built yet.

function publicProposal(row) {
    return {
        id: String(row.id),
        nodePath: row.node_path,
        type: row.type,
        displayAs: row.display_as,
        status: row.status,
        createdAt: row.created_at,
    };
}


module.exports = {
    BODY_MAX,
    CASE_MAX,
    SOURCE_MAX,
    SOURCES_MAX,
    MIN_SECONDS_ON_FORM,
    FORM_TOKEN_MAX_AGE_MS,
    knownNodePath,
    nodePathProblem,
    caseProblem,
    bodyProblem,
    displayAsProblem,
    sourcesProblem,
    cleanSources,
    issueFormToken,
    formTokenProblem,
    publicProposal,
    pathCount: PATHS.size,
};
